name: Laravel CI

on:
  push:
    branches: [ main, develop,  'feature/user-management-testing', 'feature/login-testing', 'feature/reminders-testing', 'feature/queue-type-testing' ]
  pull_request:
    branches: [ main, develop]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      pgsql:
        image: postgres:latest
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencie
        run: composer install

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --seed

      - name: Run Tests
        run: php artisan test
